module.exports = {
  stories: [{
    id: "mike",
    title: "Introduction",
    subtitle: "Subtitle",
    byline: "Mike del Castillo",
    category: "story",
    cover: "img/candle.jpg",
    content: [{
      type: "text",
      backgroundColor: "#333",
      textColor: "#FFF",
      text: "The victims of the War on Drugs continue to rise leaving thousands of families broken by the death of a loved one.",
    }, {
      type: "text",
      backgroundColor: "#333",
      textColor: "#FFF",
      text: "The stories of these victims are often those of injustice, of people oppressed by authorities who wield fear in order to pursue deceitful change.",
    }, {
      type: "text",
      backgroundColor: "#000",
      textColor: "#F22B41",
      text: "These stories often end as the lives of these victims do—in bloodshed and in tears.",
    }, {
      type: "text",
      backgroundColor: "#000",
      textColor: "#F22B41",
      text: "But the story never ends there.",
    }, {
      type: "text",
      backgroundColor: "#FFF",
      textColor: "#F22B41",
      text: "A new story begins for these left-behind victims, these orphans and widows.",
    }, {
      type: "text",
      backgroundColor: "#FFF",
      textColor: "#000",
      text: "In times of immense bereavement, how can the Church respond to provide healing to these left-behind victims?",
    }, {
      type: "text",
      backgroundColor: "#FFF",
      textColor: "#000",
      text: "The following stories embody hope inspired by teachings of the Church lived through action.",
    }, {
      type: "text",
      backgroundColor: "#555",
      textColor: "#CCC",
      text: "TH151 Project by Dani Arceno, Mike del Castillo, Mikiel Pedraja, and Meg Villena.",
    }, ],
  }, {
    id: "dani",
    title: "Image, Respect, Worth",
    subtitle: "Subtitle",
    byline: "Dani Arceno",
    category: "story",
    cover: "img/dani/005.jpg",
    content: [{
      type: "image",
      backgroundColor: "#FFF",
      textColor: "#7BC6C5",
      img: "img/dani/001.jpg",
    }, {
      type: "image",
      backgroundColor: "#FFF",
      textColor: "#7BC6C5",
      img: "img/dani/002.jpg",
    }, {
      type: "image",
      backgroundColor: "#FFF",
      textColor: "#7BC6C5",
      img: "img/dani/003.jpg",
    }, {
      type: "image",
      backgroundColor: "#FFF",
      textColor: "#FACC7D",
      img: "img/dani/004.jpg",
    }, {
      type: "image",
      backgroundColor: "#FFF",
      textColor: "#FACC7D",
      img: "img/dani/005.jpg",
    }, {
      type: "text",
      backgroundColor: "#FACC7D",
      textColor: "#FFF",
      text: "Self Image, Self Respect, Self Worth",
    }, {
      type: "text",
      backgroundColor: "#7BC6C5",
      textColor: "#FFF",
      text: "By Dani Arceno",
    }, ],
  }, {
    id: "meg",
    title: "Our Healing",
    subtitle: "Subtitle",
    byline: "Meg Villena",
    category: "story",
    cover: "img/meg/00.jpg",
    content: [{
      type: "image",
      backgroundColor: "#F22B41",
      textColor: "#fff",
      img: "img/meg/1.jpg",
    },{
      type: "image",
      backgroundColor: "#F22B41",
      textColor: "#fff",
      img: "img/meg/2.jpg",
    },{
      type: "image",
      backgroundColor: "#F22B41",
      textColor: "#fff",
      img: "img/meg/3.jpg",
    },{
      type: "image",
      backgroundColor: "#F22B41",
      textColor: "#fff",
      img: "img/meg/4.jpg",
    },{
      type: "image",
      backgroundColor: "#F22B41",
      textColor: "#fff",
      img: "img/meg/00.jpg",
    }, {
      type: "text",
      backgroundColor: "#F22B41",
      textColor: "#FFF",
      text: "Our Healing",
    }, {
      type: "text",
      backgroundColor: "#F22B41",
      textColor: "#FFF",
      text: "By Meg Villena",
    }, ],
  }, {
    id: "mikiel",
    title: "Katarungan",
    subtitle: "Subtitle",
    byline: "Mikiel PEdraja",
    category: "story",
    cover: "img/mikiel/0.jpg",
    content: [{
      type: "image",
      backgroundColor: "#fff",
      textColor: "#000",
      img: "img/mikiel/1.jpg",
    },{
      type: "image",
      backgroundColor: "#fff",
      textColor: "#000",
      img: "img/mikiel/2.jpg",
    }, {
      type: "image",
      backgroundColor: "#fff",
      textColor: "#000",
      img: "img/mikiel/3.jpg",
    },{
      type: "image",
      backgroundColor: "#fff",
      textColor: "#000",
      img: "img/mikiel/4.jpg",
    },{
      type: "text",
      backgroundColor: "#fff",
      textColor: "#000",
      text: `"Kahapon lamang ay kapiling n'ya kanyang asawa at anak Namumuhay nang tahimik sa isang munting tahanang may tuwa Ang kaligayahan ay pinutol ng isang paratang sa kanya S'ya daw ang may sala sa isang krimen na 'di naman n'ya ginawa."`,
    }, {
      type: "text",
      backgroundColor: "#000",
      textColor: "#FFF",
      text: "Katarungan",
    },{
      type: "text",
      backgroundColor: "#000",
      textColor: "#FFF",
      text: "By Mikiel Pedraja",
    }, ],
  }, ],
};
